version: "3.9"
services:
   webserver:
     build: 
      context: .
      dockerfile: Containerfile
     ports:
      - "80:80"

   db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    
    ports:
      - "3306:3306"


  #  db:    
  #     image: mysql  
  #     # volumes: 
  #     #   -    mysql-data:/var/lib/mysql
  #     environment:  
  #      MYSQL_ROOT_PASSWORD: password
  #      MYSQL_DATABASE: database 
  #      MYSQL_USER: username
  #      MYSQL_PASSWORD: password
